name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Push Hugo to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-node@v4
        with:
          node-version: '21'
    - run: npm install -g firebase-tools
    - run: node -v && firebase --version && hugo version
    - name: Hugo build and Firebase Deploy
      run: hugo && firebase use --token "${FIREBASE_TOKEN}" && firebase deploy --non-interactive --token "${FIREBASE_TOKEN}"
      with:
        FIREBASE_TOKEN: ${{ secrets.FIREBASETOKEN }}
